### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by liamdemafelix** [liamdemafelix/askred-api#1]
- Change Password
- Registration Block
- Ability to add the full name on "+Add User"
- Button "Delete" on regular users should be disabled if another user is currently logged in
- Only one user (admin) can add more accounts
- Only the user (admin) can delete accounts
- Use of multiple logins in one account is prohibited
- In adding users, special characters in username and password is prohibited
- Fix the "Remember Me" feature
- Add "Answered By" column on Answered Questions. The values are the users itself

**Comment by kiel14** [comment]
- Ability to add the full name on "+Add User"
- Button "Delete" on users should be disabled if another user is currently logged in
- Use of multiple logins in one account is prohibited

**Comment by liamdemafelix** [comment]
Fixed in commit c76c75b1b6c205eca4adb08e8be26908e5b27b3c
